version: 0.2

phases:
  install:
    commands:
      - npm i npm@latest -g
      - npm i yarn -g
      - yarn config set ignore-engines true
  pre_build:
    commands:
      # Copy VUE_APP_API_URL to API_URL so SDK can build properly
      - export API_URL=$VUE_APP_API_URL
      - yarn add $SDK_PACKAGE_NAME --save
      - yarn
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
