version: 0.2

phases:
  install:
    commands:
      - npm i npm@latest -g
  pre_build:
    commands:
      # Preparing SDK installation
      - git clone $SDK_GIT_URL -b $SDK_GIT_BRANCH _sdkjs && cd _sdkjs
      - # Copy VUE_APP_API_URL to API_URL so SDK can build properly
      - export API_URL=$VUE_APP_API_URL
      - npm install --unsafe-perm && cd ..
      # Proceed to normal dependencies installation
      - npm install
      - npm install PolymindApp/sdk-js#$SDK_GIT_BRANCH
      # Move SDK build to node_modules
      - mv _sdkjs/lib node_modules/@polymind/sdk-js/lib && rm -R _sdkjs
  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: dist
